version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: libquality-api
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=mongodb://db/libquality
      - REDIS_URL=redis://redis
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - db
      - redis
      - workers
    command: yarn start

  workers:
    image: libquality-api
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=mongodb://db/libquality
      - REDIS_URL=redis://redis
    networks:
      - app-network
    depends_on:
      - db
      - redis
    command: yarn workers

  db:
    image: mongo:4.1.8-xenial
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    networks:
      - app-network

  redis:
    image: redis
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - app-network

volumes:
  db-data:
  redis-data:

networks:
  app-network:
    driver: bridge